import type { Product } from "@/types/product";

export const products: Product[] = [
  {
    id: "1",
    name: 'MacBook Pro 14"',
    sku: "MBP14M3PRO",
    description: "Laptop Apple MacBook Pro 14.",
    manufacturer: "Apple",
    category: "Komputery",
    features: ["M3", "Retina", "Wi-Fi 6E"],
    netPrice: 8129.27,
    grossPrice: 9999,
    vat: 23,
    currency: "PLN",
    isAvailable: true,
    isLimited: false,
    minCartQuantity: 1,
    maxCartQuantity: 2,
  },
  {
    id: "2",
    name: "Galaxy S24 Ultra",
    sku: "SGS24U256",
    description: "Flagowy smartfon Samsung Galaxy.",
    manufacturer: "Samsung",
    category: "Telefony",
    features: ["5G", "AMOLED", "S Pen"],
    netPrice: 5113.82,
    grossPrice: 6299,
    vat: 23,
    currency: "PLN",
    isAvailable: true,
    isLimited: true,
    stockQuantity: 45,
    minCartQuantity: 1,
    maxCartQuantity: 2,
  },
  {
    id: "3",
    name: "Sony WH-1000XM5",
    sku: "SNWH1000XM5",
    description: "Bezprzewodowe słuchawki z redukcją hałasu.",
    manufacturer: "Sony",
    category: "RTV",
    features: ["Bluetooth", "ANC", "Hi-Res Audio"],
    netPrice: 1299.19,
    grossPrice: 1599,
    vat: 23,
    currency: "PLN",
    isAvailable: true,
    isLimited: false,
    minCartQuantity: 1,
    maxCartQuantity: 3,
  },
  {
    id: "4",
    name: "Bosch Serie 6 WAU28P40",
    sku: "BSWAU28P40",
    description: "Pralka automatyczna Bosch Serie 6.",
    manufacturer: "Bosch",
    category: "AGD",
    features: ["EcoSilence", "ActiveWater", "SpeedPerfect"],
    netPrice: 2673.98,
    grossPrice: 3299,
    vat: 23,
    currency: "PLN",
    isAvailable: false,
    isLimited: true,
    stockQuantity: 0,
    minCartQuantity: 1,
    maxCartQuantity: 1,
  },
  {
    id: "5",
    name: "Xiaomi Smart Band 8",
    sku: "XMSB8BLK",
    description: "Opaska sportowa Xiaomi Smart Band.",
    manufacturer: "Xiaomi",
    category: "Akcesoria",
    features: ["AMOLED", "Bluetooth", "Wodoodporność"],
    netPrice: 145.53,
    grossPrice: 179,
    vat: 23,
    currency: "PLN",
    isAvailable: true,
    isLimited: false,
    minCartQuantity: 1,
    maxCartQuantity: 5,
  },
  {
    id: "6",
    name: "iPad Air 11",
    sku: "IPADAIR11",
    description: "Tablet Apple iPad Air 11.",
    manufacturer: "Apple",
    category: "Tablety",
    features: ["M2", "Liquid Retina", "USB-C"],
    netPrice: 2438.21,
    grossPrice: 2999,
    vat: 23,
    currency: "PLN",
    isAvailable: true,
    isLimited: true,
    stockQuantity: 18,
    minCartQuantity: 1,
    maxCartQuantity: 2,
  },
  {
    id: "7",
    name: "Samsung Smart Monitor M7",
    sku: "SMM7U32",
    description: "Monitor Smart 4K UHD z funkcjami multimedialnymi.",
    manufacturer: "Samsung",
    category: "Monitory",
    features: ["4K", "HDR", "Smart TV"],
    netPrice: 2438.21,
    grossPrice: 2999,
    vat: 23,
    currency: "PLN",
    isAvailable: true,
    isLimited: true,
    stockQuantity: 7,
    minCartQuantity: 1,
    maxCartQuantity: 2,
  },
];
